title: t0x0sh's Blog
description: Another infosec blog
url: "https://blog.t0x0sh.org/"
plugins:
        - jekyll-sitemap
        - jekyll-minifier

jekyll-minifier:
        exclude: 'feeds.xml'

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["tables", "autolink", "strikethrough", "fenced_code_blocks"]
